version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
      nx:
        patterns:
          - "@nx/*"
          - "nx"
      spartan:
        patterns:
          - "@spartan-ng/*"
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
